//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudget.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeBudget.App.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budżet.
        /// </summary>
        internal static string AccountSetupContentViewsType_BudgetSetup {
            get {
                return ResourceManager.GetString("AccountSetupContentViewsType_BudgetSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string AccountSetupContentViewsType_CategoriesSetup {
            get {
                return ResourceManager.GetString("AccountSetupContentViewsType_CategoriesSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalia.
        /// </summary>
        internal static string AccountSetupContentViewsType_UserSetup {
            get {
                return ResourceManager.GetString("AccountSetupContentViewsType_UserSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        internal static string MainContentViewsType_Login {
            get {
                return ResourceManager.GetString("MainContentViewsType_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        internal static string MainContentViewsType_Register {
            get {
                return ResourceManager.GetString("MainContentViewsType_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Własne.
        /// </summary>
        internal static string ReportDateFilterType_Own {
            get {
                return ResourceManager.GetString("ReportDateFilterType_Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 miesięcy.
        /// </summary>
        internal static string ReportDateFilterType_SixMonths {
            get {
                return ResourceManager.GetString("ReportDateFilterType_SixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten miesiac.
        /// </summary>
        internal static string ReportDateFilterType_ThisMonth {
            get {
                return ResourceManager.GetString("ReportDateFilterType_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten rok.
        /// </summary>
        internal static string ReportDateFilterType_ThisYear {
            get {
                return ResourceManager.GetString("ReportDateFilterType_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 miesiące.
        /// </summary>
        internal static string ReportDateFilterType_ThreeMonths {
            get {
                return ResourceManager.GetString("ReportDateFilterType_ThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 miesięcy.
        /// </summary>
        internal static string ReportDateFilterType_TwelveMonths {
            get {
                return ResourceManager.GetString("ReportDateFilterType_TwelveMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        internal static string ReportFilterType_Category {
            get {
                return ResourceManager.GetString("ReportFilterType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ReportFilterType_Date {
            get {
                return ResourceManager.GetString("ReportFilterType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz.
        /// </summary>
        internal static string ReportFilterType_None {
            get {
                return ResourceManager.GetString("ReportFilterType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słupkowy.
        /// </summary>
        internal static string ReportGraphType_Bar {
            get {
                return ResourceManager.GetString("ReportGraphType.Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kołowy.
        /// </summary>
        internal static string ReportGraphType_Pie {
            get {
                return ResourceManager.GetString("ReportGraphType.Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radialny.
        /// </summary>
        internal static string ReportGraphType_Radial {
            get {
                return ResourceManager.GetString("ReportGraphType.Radial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czasowy.
        /// </summary>
        internal static string ReportGraphType_Time {
            get {
                return ResourceManager.GetString("ReportGraphType.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od najniższej.
        /// </summary>
        internal static string ReportSortDirectoryType_Asc {
            get {
                return ResourceManager.GetString("ReportSortDirectoryType_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od najwyższej.
        /// </summary>
        internal static string ReportSortDirectoryType_Desc {
            get {
                return ResourceManager.GetString("ReportSortDirectoryType_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najczęstrze.
        /// </summary>
        internal static string ReportSortType_MostUse {
            get {
                return ResourceManager.GetString("ReportSortType_MostUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        internal static string ReportSortType_Price {
            get {
                return ResourceManager.GetString("ReportSortType_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graficzny słupkowy.
        /// </summary>
        internal static string ReportType_GraphBar {
            get {
                return ResourceManager.GetString("ReportType_GraphBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graficzny kołowy.
        /// </summary>
        internal static string ReportType_GraphPie {
            get {
                return ResourceManager.GetString("ReportType_GraphPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelaryczny.
        /// </summary>
        internal static string ReportType_Table {
            get {
                return ResourceManager.GetString("ReportType_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj transakcję.
        /// </summary>
        internal static string ShortcutType_AddTransaction {
            get {
                return ResourceManager.GetString("ShortcutType_AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj transakcję.
        /// </summary>
        internal static string ShortcutType_EditTransaction {
            get {
                return ResourceManager.GetString("ShortcutType_EditTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string ShortcutType_ManageCategory {
            get {
                return ResourceManager.GetString("ShortcutType_ManageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziel transakcję.
        /// </summary>
        internal static string ShortcutType_SplitTransaction {
            get {
                return ResourceManager.GetString("ShortcutType_SplitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Własne.
        /// </summary>
        internal static string TransactionCategoriesSelectType_Own {
            get {
                return ResourceManager.GetString("TransactionCategoriesSelectType_Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Największa suma.
        /// </summary>
        internal static string TransactionCategoriesSelectType_TopAmount {
            get {
                return ResourceManager.GetString("TransactionCategoriesSelectType_TopAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najwięcej transakcji.
        /// </summary>
        internal static string TransactionCategoriesSelectType_TopCount {
            get {
                return ResourceManager.GetString("TransactionCategoriesSelectType_TopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie.
        /// </summary>
        internal static string TransactionFilterType_All {
            get {
                return ResourceManager.GetString("TransactionFilterType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatek.
        /// </summary>
        internal static string TransactionFilterType_Expense {
            get {
                return ResourceManager.GetString("TransactionFilterType_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przychód.
        /// </summary>
        internal static string TransactionFilterType_Income {
            get {
                return ResourceManager.GetString("TransactionFilterType_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatek cykliczny.
        /// </summary>
        internal static string TransactionFilterType_RegularExpense {
            get {
                return ResourceManager.GetString("TransactionFilterType_RegularExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przychód cykliczny.
        /// </summary>
        internal static string TransactionFilterType_RegularIncome {
            get {
                return ResourceManager.GetString("TransactionFilterType_RegularIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz.
        /// </summary>
        internal static string TransactionModifyActionType_Create {
            get {
                return ResourceManager.GetString("TransactionModifyActionType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string TransactionModifyActionType_Update {
            get {
                return ResourceManager.GetString("TransactionModifyActionType_Update", resourceCulture);
            }
        }
    }
}
