//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBudget.App.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeBudget.App.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od najniższej.
        /// </summary>
        internal static string ReportFilterType_Asc {
            get {
                return ResourceManager.GetString("ReportFilterType_Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od najwyższej.
        /// </summary>
        internal static string ReportFilterType_Desc {
            get {
                return ResourceManager.GetString("ReportFilterType_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najczęstrze.
        /// </summary>
        internal static string ReportFilterType_MostUse {
            get {
                return ResourceManager.GetString("ReportFilterType_MostUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz.
        /// </summary>
        internal static string ReportFilterType_None {
            get {
                return ResourceManager.GetString("ReportFilterType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słupkowy.
        /// </summary>
        internal static string ReportGraphType_Bar {
            get {
                return ResourceManager.GetString("ReportGraphType.Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kołowy.
        /// </summary>
        internal static string ReportGraphType_Pie {
            get {
                return ResourceManager.GetString("ReportGraphType.Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radialny.
        /// </summary>
        internal static string ReportGraphType_Radial {
            get {
                return ResourceManager.GetString("ReportGraphType.Radial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czasowy.
        /// </summary>
        internal static string ReportGraphType_Time {
            get {
                return ResourceManager.GetString("ReportGraphType.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        internal static string ReportSortType_Category {
            get {
                return ResourceManager.GetString("ReportSortType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ReportSortType_Date {
            get {
                return ResourceManager.GetString("ReportSortType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz.
        /// </summary>
        internal static string ReportSortType_None {
            get {
                return ResourceManager.GetString("ReportSortType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graficzny.
        /// </summary>
        internal static string ReportType_Graph {
            get {
                return ResourceManager.GetString("ReportType_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelaryczny.
        /// </summary>
        internal static string ReportType_Table {
            get {
                return ResourceManager.GetString("ReportType_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj transakcję.
        /// </summary>
        internal static string ShortcutType_AddTransaction {
            get {
                return ResourceManager.GetString("ShortcutType_AddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj transakcję.
        /// </summary>
        internal static string ShortcutType_EditTransaction {
            get {
                return ResourceManager.GetString("ShortcutType_EditTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string ShortcutType_ManageCategory {
            get {
                return ResourceManager.GetString("ShortcutType_ManageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziel transakcję.
        /// </summary>
        internal static string ShortcutType_SplitTransaction {
            get {
                return ResourceManager.GetString("ShortcutType_SplitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie.
        /// </summary>
        internal static string TransactionFilterType_All {
            get {
                return ResourceManager.GetString("TransactionFilterType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatek.
        /// </summary>
        internal static string TransactionFilterType_Expense {
            get {
                return ResourceManager.GetString("TransactionFilterType_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przychód.
        /// </summary>
        internal static string TransactionFilterType_Income {
            get {
                return ResourceManager.GetString("TransactionFilterType_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydatek cykliczny.
        /// </summary>
        internal static string TransactionFilterType_RegularExpense {
            get {
                return ResourceManager.GetString("TransactionFilterType_RegularExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przychód cykliczny.
        /// </summary>
        internal static string TransactionFilterType_RegularIncome {
            get {
                return ResourceManager.GetString("TransactionFilterType_RegularIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz.
        /// </summary>
        internal static string TransactionModifyActionType_Create {
            get {
                return ResourceManager.GetString("TransactionModifyActionType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        internal static string TransactionModifyActionType_Update {
            get {
                return ResourceManager.GetString("TransactionModifyActionType_Update", resourceCulture);
            }
        }
    }
}
